// Generated by CoffeeScript 1.6.3
(function() {
  var Router;

  Router = (function() {
    var self, users;
    self = {};
    users = require('../models/user');
    self.index = function(req, res) {
      return users.all(function(err, users) {
        console.log(users);
        if (err) {
          throw err;
        }
        return res.send(users);
      });
    };
    self.view = function(req, res) {
      return res.end('this is the index');
    };
    self.show = function(req, res) {
      return users.find({
        name: req.params.name
      }, function(err, user) {
        if (err) {
          throw err;
        }
        return res.send(user);
      });
    };
    self.create = function(req, res) {
      return users.create(req.body.user, function(err, user) {
        if (err) {
          throw err;
        }
        return res.send(user);
      });
    };
    return self;
  }).call(this);

  module.exports = Router;

}).call(this);
