// Generated by CoffeeScript 1.6.3
(function() {
  var currentEnv, sessionId;

  sessionId = function(length) {
    var id;
    if (length == null) {
      length = 8;
    }
    id = "";
    while (id.length < length) {
      id += Math.random().toString(36).substr(2);
    }
    return id.substr(0, length);
  };

  currentEnv = process.env.NODE_ENV || 'development';

  exports.appName = 'html5node-boilerplate';

  exports.env = {
    production: false,
    test: false,
    development: false
  };

  exports.env[currentEnv] = true;

  exports.server = {
    port: 3000,
    ip: '127.0.0.1'
  };

  exports.db = {
    host: '127.0.0.1',
    port: 27017,
    name: exports.appName.toLowerCase()
  };

  if (currentEnv !== 'production') {
    exports.enableTests = true;
    exports.server.ip = '0.0.0.0';
  }

}).call(this);
