// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    var resource, users;
    resource = require('express-resource');
    users = require('../routes/users');
    return app.resource('users', users);
  };

}).call(this);
